Bumping black version in CI
The previous version would produce an error (presumably due to changes
in its click dependency):

    ImportError: cannot import name '_unicodefun' from 'click' (/home/matthijs/docs/src/upstream/django-konst/.tox/checkqa/lib/python3.11/site-packages/click/__init__.py)